# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

goals = Goal.create([{name: 'eat a vegetable', goal_type: 'body'}, {name: 'take a deep breath', goal_type: 'body'}, {name: 'drink a gallon of water', goal_type: 'body'}, {name: 'walk at least a mile', goal_type: 'body'}, {name: 'exercise for 45 minutes', goal_type: 'body'}, {name: 'floss at least once', goal_type: 'body'}, {name: 'do two practice Javascript problems', goal_type: 'mind'}, {name: 'learn one new word and use it in conversation', goal_type: 'mind'}, {name: 'read the news', goal_type: 'mind'}, {name: 'watch less television', goal_type: 'mind'}, {name: 'pack lunch instead of buying lunch', goal_type: 'personal growth'}, {name: 'smell the roses', goal_type: 'personal growth'}, {name: 'surprise yourself', goal_type: 'personal growth'}, {name: 'write down your ideas', goal_type: 'personal growth'}, {name: 'research new opportunities', goal_type: 'personal growth'}, {name: 'wake up before the sun', goal_type: 'personal growth'}, {name: 'avoid hitting snooze', goal_type: 'personal growth'}, {name: 'tweet twice', goal_type: 'social'},{name: 'give your pet undivided attention for 15 minutes', goal_type: 'social'},{name: 'meet someone new', goal_type: 'social'}, {name: 'distract someone', goal_type: 'social'}, {name: 'fight the power', goal_type: 'world takeover'}, {name: 'work on the details of your zombie apocalypse plan', goal_type: 'world takeover'}, {name: 'do something hedonistic', goal_type: 'world takeover'}, {name: 'get on your soap box', goal_type: 'worls takeover'}, {name: 'check Facebook only once', goal_type: 'social'}, {name: 'give an affirmation', goal_type: 'social'}, {name: 'write in your journal', goal_type: 'personal growth'}, {name: 'find inspiration', goal_type: 'personal growth'}, {name: 'water the plants', goal_type: 'personal growth'}, {name: 'give someone a high five', goal_type: 'social'}])
Award.create([{name:"Hacker",desc:"You shouldn't have this badge cheater!",image_url:"Badge_voodoo.png"}, {name:"Newbie", desc:"Add a goal to your list.", image_url:"Badge_newgoal.png"}, {name:"Intro to your Body", desc:"Add a body goal.", image_url:"Badge_levitation.png"}, {name:"Quick Starter",desc:"Do not hit snooze for three days in a row.",image_url:"Badge_clock.png"}, {name:"3 X 3",desc:"Keep three goals for 3 days in a row at the same time.",image_url:"Badge_trophy.png"}, {name:"10 Spot",desc:"Have ten active goals.",image_url:"Badge_awkwardface.png"}])